---
title: "Liberia Coverage Assessment of Direct Nutrition Interventions"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
#runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
if(!require(remotes)) install.packages("remotes")
if(!require(liberia)) install_github("validmeasures/liberia")
#if(!require(liberiaData)) install_github("validmeasures/liberiaData")
if(!require(gstat)) install.packages("gstat")
if(!require(rgdal)) install.packages("rgdal")
if(!require(rgeos)) install.packages("rgeos")
if(!require(raster)) install.packages("raster")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(ggplot2)) install.packages("ggplot2")

#
# Create Mapbox base layer objects for leaflet mapping
#
mapbox.satellite <- "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.street    <- "https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.dark      <- "https://api.mapbox.com/styles/v1/mapbox/dark-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.light     <- "https://api.mapbox.com/styles/v1/mapbox/light-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.moonlight <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj3nban30001z2rpahc10c9ef/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.northstar <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj4ke832y4sng2spe2ds4fs55/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.standard  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5di36jn0gxg2rphjn3yetpt/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.decimal   <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5ms1akt3pbi2smtcewsex9m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.terminal  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj6g0tzbd30kc2sph2wyh666m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"

load("gmHexGrid.rda")
load("ifaInt.rda")

ifaInt <- ifaInt[["Greater Monrovia"]]

monrovia <- subset(liberia::districts, admin2Name == "Greater Monrovia")
gmLng1 <- bbox(monrovia)[1, 1]
gmLat1 <- bbox(monrovia)[2, 1]
gmLng2 <- bbox(monrovia)[1, 2]
gmLat2 <- bbox(monrovia)[2, 2]

#grandBassa <- subset(liberia::counties, admin1name == "Grand Bassa")
#gbLng1 <- bbox(grandBassa)[1, 1]
#gbLat1 <- bbox(grandBassa)[2, 1]
#gbLng2 <- bbox(grandBassa)[1, 2]
#gbLat2 <- bbox(grandBassa)[2, 2]
```

Urban Montserrado
================================================================================

Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### IFA

```{r ifaGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, ifaInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa1),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa1),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa1 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Attended ANC"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa2),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa2),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa2 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Know/heard of IFA"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa3),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa3),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa3 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Received/purchased IFA"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa4),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa4),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa4 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Took IFA"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Attended ANC", "Know/heard of IFA", "Received/purchased IFA", "Took IFA"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

